train:
  #- challenge_cispd
  #- challenge_realpd
test:
  #- challenge_cispd
  #- challenge_realpd
  - community_cispd_clinic_tasks
  #- community_cispd_updrs
  #- community_realpd_hauser_diary
  #- community_realpd_updrs